apiVersion: v1
kind: Pod
metadata:
  name: redis-stack
spec:
  nodeSelector:
    type: app
  containers:
  - name: redis-stack
    image: "redis/redis-stack:latest"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
      - name: http
        containerPort: 8001
        protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi