spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb?MODE=MYSQL}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 500

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub

decorator:
  datasource:
    p6spy:
      enable-logging: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
